import sys
sys.path.insert(0, 'scripts')
from minicheck_lib import mc, lueck, rech, block, L, apply_page

p53 = [
 ('definition', block([
   mc(r"Warum haben Schienen und Brücken Dehnungsfugen?",
      [("A", r"um Material zu sparen"), ("B", r"damit sich das Material bei Erwärmung ausdehnen kann"), ("C", r"aus optischen Gründen")],
      r"<strong>B.</strong> Ohne Fugen würde sich das erwärmte Material verbiegen oder Spannungen aufbauen."),
   lueck(r"Die meisten Stoffe dehnen sich beim Erwärmen " + L + r".",
      r"aus."),
   rech(r"Eine \(10\;\text{m}\)-Stahlschiene (\(\alpha = 12\cdot 10^{-6}\;\text{1/K}\)) erwärmt sich um \(\Delta T = 30\;\text{K}\). Längenänderung?",
      r"\(\Delta l = \alpha\,l_0\,\Delta T = 12\cdot 10^{-6} \cdot 10 \cdot 30 = 3.6\cdot 10^{-3}\;\text{m} = 3.6\;\text{mm}\)."),
 ],
  r"Warum verlegt man Hochspannungsleitungen im Sommer absichtlich leicht durchhängend?",
  r"Bei Kälte zieht sich das Kabel zusammen. Wäre es straff verlegt, könnte es im Winter reissen. Der Durchhang gibt Spielraum für die thermische Längenänderung.")),
 ('laenge', block([
   mc(r"Der lineare Ausdehnungskoeffizient \(\alpha\) gibt an …",
      [("A", r"die relative Längenänderung pro Grad Temperaturänderung"), ("B", r"die Masse pro Volumen"), ("C", r"die zugeführte Wärmemenge")],
      r"<strong>A.</strong> \(\alpha\) ist die relative Längenänderung je Kelvin (Einheit \(\text{1/K}\))."),
   lueck(r"Die Längenausdehnung ist \(\Delta l = \alpha \cdot l_0 \cdot\) " + L + r".",
      r"\(\Delta T\)."),
   rech(r"Alustange (\(\alpha = 23\cdot 10^{-6}\)), \(l_0 = 2\;\text{m}\), \(\Delta T = 50\;\text{K}\). Längenänderung?",
      r"\(\Delta l = 23\cdot 10^{-6} \cdot 2 \cdot 50 = 2.3\cdot 10^{-3}\;\text{m} = 2.3\;\text{mm}\)."),
 ],
  r"Ein Bimetallstreifen (zwei verbundene Metalle mit verschiedenem \(\alpha\)) krümmt sich beim Erwärmen. Warum?",
  r"Das Metall mit grösserem \(\alpha\) dehnt sich stärker. Die feste Verbindung zwingt den Streifen, sich zur Seite des kleineren \(\alpha\) zu krümmen — die Grundlage von Thermostaten.")),
 ('volumen', block([
   mc(r"Verdoppelt man die Temperaturdifferenz, so wird die Längenänderung …",
      [("A", r"doppelt so gross"), ("B", r"viermal so gross"), ("C", r"gleich gross")],
      r"<strong>A.</strong> \(\Delta l \sim \Delta T\) — doppelte Temperaturdifferenz, doppelte Längenänderung."),
   lueck(r"Die Längenänderung ist proportional zur " + L + r" und zur Temperaturdifferenz.",
      r"Ausgangslänge \(l_0\)."),
   rech(r"Eine \(50\;\text{m}\)-Brücke (\(\alpha = 12\cdot 10^{-6}\)) erwärmt sich um \(40\;\text{K}\). Längenänderung?",
      r"\(\Delta l = 12\cdot 10^{-6} \cdot 50 \cdot 40 = 0.024\;\text{m} = 2.4\;\text{cm}\)."),
 ],
  r"Eine \(100\;\text{m}\)-Schiene (\(\alpha = 12\cdot 10^{-6}\)) soll sich bei \(\Delta T = 35\;\text{K}\) frei dehnen. Wie breit muss die Fuge mindestens sein?",
  r"\(\Delta l = 12\cdot 10^{-6} \cdot 100 \cdot 35 = 0.042\;\text{m} = 4.2\;\text{cm}\).")),
 ('anomalie', block([
   mc(r"Für die Volumenausdehnung von Festkörpern gilt näherungsweise …",
      [("A", r"\(\gamma = \alpha\)"), ("B", r"\(\gamma \approx 3\alpha\)"), ("C", r"\(\gamma \approx \alpha/3\)")],
      r"<strong>B.</strong> Da sich der Körper in drei Raumrichtungen ausdehnt, gilt \(\gamma \approx 3\alpha\)."),
   lueck(r"Die Volumenausdehnung ist \(\Delta V = \gamma \cdot V_0 \cdot\) " + L + r".",
      r"\(\Delta T\)."),
   rech(r"Ein Festkörper hat \(\alpha = 10\cdot 10^{-6}\). Wie gross ist \(\gamma\) näherungsweise?",
      r"\(\gamma \approx 3\alpha = 30\cdot 10^{-6}\;\text{1/K}\)."),
 ],
  r"Warum läuft ein randvoll gefüllter Wassertopf beim Erhitzen über, obwohl auch der Topf sich ausdehnt?",
  r"Wasser hat ein viel grösseres \(\gamma\) als das Metall des Topfs. Das Wasservolumen wächst stärker als der Topfinnenraum, daher fliesst Wasser über.")),
 ('meeresspiegel', block([
   mc(r"Wasser hat seine grösste Dichte bei …",
      [("A", r"\(0°C\)"), ("B", r"\(4°C\)"), ("C", r"\(100°C\)")],
      r"<strong>B.</strong> Die Anomalie des Wassers: maximale Dichte bei \(4°C\)."),
   lueck(r"Beim Abkühlen unter \(4°C\) " + L + r" sich Wasser wieder aus.",
      r"dehnt."),
   rech(r"Bei welcher Temperatur sammelt sich im Winter das dichteste Wasser am Seeboden?",
      r"Bei \(4°C\) — dort ist Wasser am dichtesten und sinkt nach unten."),
 ],
  r"Warum gefriert ein See von oben nach unten und nicht umgekehrt?",
  r"Das dichteste Wasser (\(4°C\)) sinkt nach unten; kälteres, leichteres Wasser bleibt oben und gefriert dort zuerst. Die Eisschicht isoliert das Wasser darunter, sodass Fische überleben.")),
 ('gasgesetz', block([
   mc(r"Ein wesentlicher Beitrag zum Meeresspiegelanstieg ist …",
      [("A", r"mehr gelöstes Salz"), ("B", r"die thermische Ausdehnung des erwärmten Wassers"), ("C", r"die Anziehung des Mondes")],
      r"<strong>B.</strong> Wärmeres Meerwasser dehnt sich aus und braucht mehr Volumen."),
   lueck(r"Erwärmtes Meerwasser nimmt mehr " + L + r" ein.",
      r"Volumen (Raum)."),
   rech(r"Eine \(4000\;\text{m}\) tiefe Wassersäule (\(\gamma = 0.21\cdot 10^{-3}\;\text{1/K}\)) erwärmt sich um \(1\;\text{K}\). Höhenzunahme?",
      r"\(\Delta h = \gamma\,h_0\,\Delta T = 0.21\cdot 10^{-3} \cdot 4000 \cdot 1 = 0.84\;\text{m}\)."),
 ],
  r"Warum trägt die thermische Ausdehnung global stark zum Meeresspiegel bei, obwohl \(\gamma\) für Wasser klein ist?",
  r"Der Ozean ist im Mittel mehrere Kilometer tief. Selbst eine kleine relative Ausdehnung über diese riesige Säulenhöhe \(h_0\) ergibt einen merklichen Anstieg \(\Delta h = \gamma\,h_0\,\Delta T\).")),
 ('diagramme', block([
   mc(r"Das allgemeine Gasgesetz lautet …",
      [("A", r"\(pV = \text{const}\)"), ("B", r"\(\dfrac{pV}{T} = \text{const}\)"), ("C", r"\(\dfrac{p}{V} = \text{const}\)")],
      r"<strong>B.</strong> \(\dfrac{pV}{T} = \text{const}\) — \(T\) stets in Kelvin."),
   lueck(r"Im allgemeinen Gasgesetz muss die Temperatur in " + L + r" eingesetzt werden.",
      r"Kelvin."),
   rech(r"Ein Gas (\(2\;\text{L}\), \(300\;\text{K}\), konstanter Druck) wird auf \(600\;\text{K}\) erwärmt. Neues Volumen?",
      r"\(V_2 = V_1 \cdot \dfrac{T_2}{T_1} = 2 \cdot \dfrac{600}{300} = 4\;\text{L}\)."),
 ],
  r"Ein geschlossener Behälter (festes Volumen) mit Gas wird von \(300\;\text{K}\) auf \(450\;\text{K}\) erwärmt, Anfangsdruck \(1\;\text{bar}\). Neuer Druck?",
  r"Bei konstantem Volumen: \(p_2 = p_1 \cdot \dfrac{T_2}{T_1} = 1 \cdot \dfrac{450}{300} = 1.5\;\text{bar}\).")),
 ('aufgaben', block([
   mc(r"Bei konstanter Temperatur (Gesetz von Boyle): verdoppelt man den Druck, so …",
      [("A", r"verdoppelt sich das Volumen"), ("B", r"halbiert sich das Volumen"), ("C", r"bleibt das Volumen gleich")],
      r"<strong>B.</strong> \(p\,V = \text{const}\) → doppelter Druck, halbes Volumen."),
   lueck(r"Bei konstanter Temperatur ist das Produkt \(p\cdot V\) " + L + r".",
      r"konstant."),
   rech(r"Gas: \(p_1 = 2\;\text{bar}\), \(V_1 = 3\;\text{L}\) bei konstanter Temperatur. Volumen bei \(p_2 = 6\;\text{bar}\)?",
      r"\(V_2 = \dfrac{p_1 V_1}{p_2} = \dfrac{2 \cdot 3}{6} = 1\;\text{L}\)."),
 ],
  r"Bei konstanter Temperatur ergibt das \(p\)-\(V\)-Diagramm eine Hyperbel, bei konstantem Volumen das \(p\)-\(T\)-Diagramm eine Ursprungsgerade. Warum diese verschiedenen Formen?",
  r"Boyle: \(pV = \text{const} \Rightarrow p \sim 1/V\) (Hyperbel). Amontons: \(p/T = \text{const} \Rightarrow p \sim T\) (Gerade durch den Nullpunkt, in Kelvin). Verschiedene Proportionalitäten, verschiedene Kurven.")),
]

p61 = [
 ('definition', block([
   mc(r"Bei einer Wasserwelle transportiert die Welle hauptsächlich …",
      [("A", r"Wasser"), ("B", r"Energie"), ("C", r"Masse")],
      r"<strong>B.</strong> Eine Welle transportiert Energie; das Medium schwingt nur um seine Ruhelage."),
   lueck(r"Eine Welle überträgt Energie, ohne " + L + r" zu transportieren.",
      r"Materie (Masse)."),
   rech(r"Eine Welle hat \(f = 2\;\text{Hz}\). Welche Periodendauer?",
      r"\(T = \dfrac{1}{f} = \dfrac{1}{2} = 0.5\;\text{s}\)."),
 ],
  r"Eine Möwe sitzt auf einer Wasserwelle. Wie bewegt sie sich, während Wellen unter ihr durchlaufen?",
  r"Sie schwingt im Wesentlichen auf der Stelle auf und ab und wird nicht mit der Welle mittransportiert — die Welle trägt Energie, nicht Wasser.")),
 ('wellengleichung', block([
   mc(r"Die Wellenlänge \(\lambda\) ist …",
      [("A", r"die Höhe der Welle"), ("B", r"der Abstand zweier gleicher Phasen (z.B. Berg zu Berg)"), ("C", r"die Geschwindigkeit")],
      r"<strong>B.</strong> \(\lambda\) ist der räumliche Abstand zweier benachbarter gleicher Phasen."),
   lueck(r"Die Anzahl Schwingungen pro Sekunde ist die " + L + r".",
      r"Frequenz \(f\)."),
   rech(r"Eine Welle hat \(T = 0.25\;\text{s}\). Frequenz?",
      r"\(f = \dfrac{1}{T} = \dfrac{1}{0.25} = 4\;\text{Hz}\)."),
 ],
  r"Was hört man bei einer Schallwelle als Folge ihrer Amplitude, was als Folge ihrer Frequenz?",
  r"Die Amplitude bestimmt die Lautstärke, die Frequenz die Tonhöhe.")),
 ('typen', block([
   mc(r"Bei gleicher Wellengeschwindigkeit bedeutet eine höhere Frequenz …",
      [("A", r"eine grössere Wellenlänge"), ("B", r"eine kleinere Wellenlänge"), ("C", r"die gleiche Wellenlänge")],
      r"<strong>B.</strong> \(\lambda = c/f\) — höhere Frequenz, kleinere Wellenlänge."),
   lueck(r"Die Wellengleichung lautet \(c = \lambda \cdot\) " + L + r".",
      r"\(f\) (Frequenz)."),
   rech(r"Schall (\(c = 340\;\text{m/s}\)) mit \(f = 170\;\text{Hz}\). Wellenlänge?",
      r"\(\lambda = \dfrac{c}{f} = \dfrac{340}{170} = 2\;\text{m}\)."),
 ],
  r"Ein UKW-Sender sendet bei \(f = 100\;\text{MHz}\) (\(c = 3\cdot 10^8\;\text{m/s}\)). Welche Wellenlänge?",
  r"\(\lambda = \dfrac{c}{f} = \dfrac{3\cdot 10^8}{1\cdot 10^8} = 3\;\text{m}\).")),
 ('schall', block([
   mc(r"Bei einer Longitudinalwelle schwingen die Teilchen …",
      [("A", r"senkrecht zur Ausbreitungsrichtung"), ("B", r"parallel zur Ausbreitungsrichtung"), ("C", r"gar nicht")],
      r"<strong>B.</strong> Bei Longitudinalwellen (z.B. Schall) schwingen die Teilchen längs der Ausbreitung."),
   lueck(r"Schall in Luft ist eine " + L + r" Welle.",
      r"longitudinale."),
   rech(r"Nenne ein Beispiel für eine Transversalwelle.",
      r"Eine Welle auf einem gespannten Seil oder eine Lichtwelle (Teilchen schwingen quer zur Ausbreitung)."),
 ],
  r"Wasserwellen werden oft als transversal bezeichnet. Warum stimmt das nur ungefähr?",
  r"An der Oberfläche bewegen sich die Wasserteilchen auf kreis- bis ellipsenförmigen Bahnen — also teils längs, teils quer. Eine reine Transversalbewegung ist es nicht.")),
 ('spektrum', block([
   mc(r"Schall breitet sich am schnellsten aus in …",
      [("A", r"Luft"), ("B", r"Wasser"), ("C", r"Stahl")],
      r"<strong>C.</strong> In festen, eng gebundenen Stoffen wie Stahl ist die Schallgeschwindigkeit am grössten."),
   lueck(r"Im Vakuum kann sich Schall " + L + r" ausbreiten.",
      r"nicht — Schall braucht ein Medium."),
   rech(r"Du hörst den Donner \(3\;\text{s}\) nach dem Blitz (\(c \approx 340\;\text{m/s}\)). Entfernung?",
      r"\(s = c\cdot t = 340 \cdot 3 = 1020\;\text{m} \approx 1\;\text{km}\)."),
 ],
  r"Warum hört man bei einem fernen Gewitter Blitz und Donner deutlich versetzt, bei einem nahen kaum?",
  r"Licht ist praktisch sofort da, Schall braucht rund \(3\;\text{s}\) pro Kilometer. Bei grosser Entfernung ist der Laufzeitunterschied gross, bei kleiner kaum merklich.")),
 ('emission', block([
   mc(r"Welche dieser Wellen hat die kürzeste Wellenlänge?",
      [("A", r"Radiowellen"), ("B", r"sichtbares Licht"), ("C", r"Röntgenstrahlung")],
      r"<strong>C.</strong> Röntgenstrahlung hat die höchste Frequenz und damit die kürzeste Wellenlänge."),
   lueck(r"Alle elektromagnetischen Wellen breiten sich im Vakuum mit der " + L + r" aus.",
      r"Lichtgeschwindigkeit \(c\)."),
   rech(r"Ordne nach steigender Frequenz: Infrarot, sichtbares Licht, UV.",
      r"Infrarot \(<\) sichtbares Licht \(<\) UV."),
 ],
  r"Warum bräunt UV-Strahlung die Haut, sichtbares Licht aber nicht?",
  r"UV hat eine höhere Frequenz und damit nach \(E = h f\) energiereichere Photonen. Diese Energie reicht aus, um in der Haut Prozesse auszulösen; sichtbares Licht ist dafür zu energiearm.")),
 ('absorption', block([
   mc(r"Die Energie eines Photons ist …",
      [("A", r"proportional zur Wellenlänge"), ("B", r"proportional zur Frequenz"), ("C", r"für alle Photonen gleich")],
      r"<strong>B.</strong> \(E = h f\) — die Photonenenergie wächst mit der Frequenz."),
   lueck(r"Die Photonenenergie ist \(E = h \cdot\) " + L + r".",
      r"\(f\) (Frequenz)."),
   rech(r"Was zeichnet Laserlicht gegenüber Glühlampenlicht aus?",
      r"Es ist einfarbig (eine Frequenz), kohärent (gleiche Phase) und stark gebündelt."),
 ],
  r"Warum leuchten verschiedene Gase in Leuchtröhren in verschiedenen Farben?",
  r"Jedes Atom emittiert nur bestimmte Frequenzen (Übergänge zwischen festen Energieniveaus). Diese diskreten Linien ergeben die charakteristische Farbe — das Linienspektrum des Elements.")),
 ('aufgaben', block([
   mc(r"Treibhausgase absorbieren vor allem …",
      [("A", r"sichtbares Licht"), ("B", r"infrarote Strahlung"), ("C", r"Radiowellen")],
      r"<strong>B.</strong> Treibhausgase absorbieren die infrarote (Wärme-)Strahlung der Erde."),
   lueck(r"Ob eine Welle absorbiert wird, hängt von ihrer " + L + r" ab.",
      r"Wellenlänge (Frequenz)."),
   rech(r"In welchem Bereich strahlt die Erde, dessen Strahlung von \(\text{CO}_2\) teils absorbiert wird?",
      r"Im Infrarot — die langwellige Wärmestrahlung der Erdoberfläche."),
 ],
  r"Warum erscheint ein rotes T-Shirt rot?",
  r"Es absorbiert die übrigen Wellenlängen des sichtbaren Lichts und reflektiert vorwiegend das rote. Diese reflektierte Wellenlänge gelangt ins Auge.")),
]

assert 1/2 == 0.5 and 1/0.25 == 4 and 340/170 == 2 and 3e8/1e8 == 3 and 340*3 == 1020
assert 12e-6*10*30 == 3.6e-3 and 23e-6*2*50 == 2.3e-3 and 12e-6*50*40 == 0.024 and 12e-6*100*35 == 0.042
assert round(3*10e-6,9) == round(30e-6,9) and round(0.21e-3*4000*1,2) == 0.84 and 2*600/300 == 4 and 1*450/300 == 1.5 and 2*3/6 == 1
print("Zahlen p5-3 & p6-1: OK")

for fn, pairs in [("themen/p5-3-waermeausdehnung.html", p53), ("themen/p6-1-wellen.html", p61)]:
    n, do_, dc, oo, oc = apply_page(fn, pairs)
    print(f"{fn}: {n} Mini-Checks | div {do_}/{dc} {'OK' if do_==dc else 'DIFF'} | open( {oo}/{oc} {'OK' if oo==oc else 'DIFF'}")
