import sys, math
sys.path.insert(0, 'scripts')
from minicheck_lib import mc, lueck, rech, block, L, apply_page

p42 = [
 ('definition', block([
   mc(r"Warum schwappt das Glas, wenn die Theke (der Wagen) ruckartig anfährt?",
      [("A", r"Das Wasser wird nach vorne gedrückt."), ("B", r"Das Wasser bleibt wegen seiner Trägheit zurück."), ("C", r"Die Schwerkraft nimmt zu.")],
      r"<strong>B.</strong> Das Wasser behält seinen Bewegungszustand bei (Trägheit); der Wagen beschleunigt darunter weg."),
   lueck(r"Ein Körper behält ohne resultierende äussere Kraft seinen " + L + r" bei.",
      r"Bewegungszustand (Trägheitsgesetz)."),
   rech(r"Welche Kraft beschleunigt eine Masse von \(2\;\text{kg}\) mit \(3\;\text{m/s}^2\)?",
      r"\(F = m\cdot a = 2 \cdot 3 = 6\;\text{N}\)."),
 ],
  r"Im anfahrenden Bus wirst du nach hinten gedrückt, obwohl keine Kraft nach hinten wirkt. Wie erklärt sich das?",
  r"Dein Körper behält seine Ruhe bei (Trägheit), der Bus beschleunigt unter dir nach vorne. Relativ zum Bus bewegst du dich nach hinten — eine Scheinkraft, keine echte rückwärts gerichtete Kraft.")),
 ('federkraft', block([
   mc(r"Die SI-Einheit der Kraft ist …",
      [("A", r"Joule"), ("B", r"Newton"), ("C", r"Watt")],
      r"<strong>B.</strong> Die Kraft wird in Newton gemessen: \(1\;\text{N} = 1\;\text{kg}\cdot\text{m/s}^2\)."),
   lueck(r"Eine Kraft ist eine " + L + r" Grösse — sie besitzt Betrag und Richtung.",
      r"vektorielle (im Gegensatz zur skalaren Masse)."),
   rech(r"Wie gross ist die Gewichtskraft einer Masse von \(5\;\text{kg}\)? (\(g = 9.81\;\text{m/s}^2\))",
      r"\(F_G = m\cdot g = 5 \cdot 9.81 = 49.05\;\text{N}\)."),
 ],
  r"Ein Astronaut hat auf dem Mond (\(g_M \approx 1.62\;\text{m/s}^2\)) dieselbe Masse wie auf der Erde. Was ändert sich, was bleibt gleich?",
  r"Die Masse bleibt gleich (Stoffeigenschaft). Die Gewichtskraft sinkt: \(F = m\,g_M\), also rund ein Sechstel der Erd-Gewichtskraft.")),
 ('grundgesetz', block([
   mc(r"Verdoppelt man die Dehnung einer Feder, so …",
      [("A", r"bleibt die Kraft gleich"), ("B", r"verdoppelt sich die Kraft"), ("C", r"vervierfacht sich die Kraft")],
      r"<strong>B.</strong> Nach \(F = D\cdot s\) ist die Kraft proportional zur Dehnung."),
   lueck(r"Im Hookeschen Gesetz ist die Federkraft " + L + r" zur Dehnung.",
      r"proportional — \(F = D\cdot s\)."),
   rech(r"Eine Feder mit \(D = 200\;\text{N/m}\) wird um \(s = 0.15\;\text{m}\) gedehnt. Federkraft?",
      r"\(F = D\cdot s = 200 \cdot 0.15 = 30\;\text{N}\)."),
 ],
  r"Zwei gleiche Federn (je \(D = 200\;\text{N/m}\)) werden parallel an dieselbe Last gehängt. Welche Federkonstante hat die Kombination?",
  r"Parallel addieren sich die Federkonstanten: \(D_{\text{ges}} = D_1 + D_2 = 400\;\text{N/m}\) — die Anordnung ist steifer.")),
 ('traegheit', block([
   mc(r"Bei gleicher Kraft erfährt die doppelte Masse …",
      [("A", r"die doppelte Beschleunigung"), ("B", r"die halbe Beschleunigung"), ("C", r"dieselbe Beschleunigung")],
      r"<strong>B.</strong> Aus \(a = F/m\) folgt: doppelte Masse → halbe Beschleunigung."),
   lueck(r"Das Grundgesetz der Mechanik lautet \(F = m \cdot\) " + L + r".",
      r"\(a\) — Kraft gleich Masse mal Beschleunigung."),
   rech(r"Welche Beschleunigung erfährt \(m = 4\;\text{kg}\) unter \(F = 12\;\text{N}\)?",
      r"\(a = \dfrac{F}{m} = \dfrac{12}{4} = 3\;\text{m/s}^2\)."),
 ],
  r"Eine Kraft von \(20\;\text{N}\) wirkt \(3\;\text{s}\) lang auf einen ruhenden Körper (\(m = 5\;\text{kg}\)). Welche Geschwindigkeit erreicht er?",
  r"\(a = \dfrac{F}{m} = \dfrac{20}{5} = 4\;\text{m/s}^2\); \(\;\; v = a\cdot t = 4 \cdot 3 = 12\;\text{m/s}\).")),
 ('reibung', block([
   mc(r"Auf einen Körper wirkt keine resultierende Kraft. Dann …",
      [("A", r"bleibt er in Ruhe oder bewegt sich gleichförmig weiter"), ("B", r"bleibt er immer stehen"), ("C", r"beschleunigt er gleichmässig")],
      r"<strong>A.</strong> Ohne resultierende Kraft bleibt der Bewegungszustand erhalten (Trägheitsgesetz)."),
   lueck(r"Das Trägheitsgesetz ist das " + L + r" Newtonsche Gesetz.",
      r"erste (1.)."),
   rech(r"Ein Puck gleitet reibungsfrei mit \(8\;\text{m/s}\). Welche Kraft hält ihn in konstanter Bewegung?",
      r"Keine — \(F = 0\;\text{N}\). Ohne Reibung bleibt die Geschwindigkeit von selbst erhalten."),
 ],
  r"Warum wird man bei einer Vollbremsung nach vorne geschleudert, wenn man nicht angeschnallt ist?",
  r"Wegen der Trägheit behält der Körper seine Geschwindigkeit, während das Auto bremst. Ohne Gurt wirkt keine bremsende Kraft auf den Körper.")),
 ('schiefe-ebene', block([
   mc(r"Die maximale Haftreibung ist bei den meisten Materialpaarungen …",
      [("A", r"kleiner als die Gleitreibung"), ("B", r"grösser als die Gleitreibung"), ("C", r"genau gleich gross")],
      r"<strong>B.</strong> Erst muss die Haftreibung überwunden werden; danach fällt die Reibung auf den kleineren Gleitwert."),
   lueck(r"Die Reibungskraft hängt von der Normalkraft ab: \(F_R = \mu \cdot\) " + L + r".",
      r"\(F_N\) — Reibungszahl mal Normalkraft."),
   rech(r"Ein Klotz drückt mit \(F_N = 50\;\text{N}\), \(\mu_G = 0.30\). Gleitreibung?",
      r"\(F_G = \mu_G \cdot F_N = 0.30 \cdot 50 = 15\;\text{N}\)."),
 ],
  r"Warum bremst ein Auto mit blockierenden Rädern schlechter als eines mit ABS (Räder kurz vor dem Blockieren)?",
  r"Blockierte Räder gleiten — es wirkt die kleinere Gleitreibung. Rollende Räder nutzen die grössere maximale Haftreibung, daher kürzerer Bremsweg.")),
 ('wechselwirkung', block([
   mc(r"Beim Erhöhen des Neigungswinkels nimmt die Hangabtriebskraft …",
      [("A", r"ab"), ("B", r"zu"), ("C", r"bleibt gleich")],
      r"<strong>B.</strong> \(F_H = m g \sin\alpha\) — mit grösserem \(\alpha\) wächst \(\sin\alpha\)."),
   lueck(r"Die Hangabtriebskraft ist \(F_H = m g \cdot\) " + L + r" des Neigungswinkels.",
      r"dem Sinus — \(F_H = m g \sin\alpha\)."),
   rech(r"Körper (\(m = 2\;\text{kg}\)) auf einer Ebene mit \(\alpha = 30°\). Hangabtriebskraft? (\(g = 9.81\), \(\sin 30° = 0.5\))",
      r"\(F_H = m g \sin\alpha = 2 \cdot 9.81 \cdot 0.5 = 9.81\;\text{N}\)."),
 ],
  r"Ab welchem Neigungswinkel beginnt ein Körper zu rutschen, wenn \(\mu_H = 0.5\)?",
  r"Rutschbeginn bei \(\tan\alpha = \mu_H\): \(\alpha = \arctan(0.5) \approx 26.6°\) — unabhängig von der Masse.")),
 ('aufgaben', block([
   mc(r"Du drückst mit \(50\;\text{N}\) gegen eine feste Wand. Wie gross ist die Gegenkraft der Wand auf dich?",
      [("A", r"\(0\;\text{N}\)"), ("B", r"\(50\;\text{N}\)"), ("C", r"hängt von der Wand ab")],
      r"<strong>B.</strong> Nach actio = reactio drückt die Wand mit genau \(50\;\text{N}\) zurück."),
   lueck(r"Kraft und Gegenkraft sind gleich gross und " + L + r" gerichtet.",
      r"entgegengesetzt — sie greifen an verschiedenen Körpern an."),
   rech(r"Eine Rakete stösst Gas mit \(F = 8000\;\text{N}\) nach unten. Schubkraft nach oben?",
      r"\(8000\;\text{N}\) — die Gegenkraft ist gleich gross und entgegengesetzt."),
 ],
  r"Zwei Schlittschuhläufer (\(60\;\text{kg}\) und \(40\;\text{kg}\)) stossen sich ab. Der schwerere gleitet mit \(2\;\text{m/s}\) weg. Wie schnell der leichtere?",
  r"Impulserhaltung: \(m_1 v_1 = m_2 v_2 \Rightarrow 60 \cdot 2 = 40 \cdot v_2 \Rightarrow v_2 = 3\;\text{m/s}\).")),
]

p43 = [
 ('definition', block([
   mc(r"Woher nimmt die Achterbahn nach dem ersten Hügel ihre Bewegung?",
      [("A", r"aus einem versteckten Motor"), ("B", r"aus der Umwandlung von Lage- in Bewegungsenergie"), ("C", r"aus der Reibung")],
      r"<strong>B.</strong> Die im ersten Hügel gespeicherte Lageenergie wird beim Hinunterfahren in Bewegungsenergie umgewandelt."),
   lueck(r"Energie kann nicht erzeugt oder vernichtet, nur " + L + r" werden.",
      r"umgewandelt (Energieerhaltung)."),
   rech(r"Lageenergie eines Wagens (\(m = 500\;\text{kg}\)) in \(h = 20\;\text{m}\) Höhe? (\(g = 9.81\))",
      r"\(E_{\text{pot}} = m g h = 500 \cdot 9.81 \cdot 20 = 98\,100\;\text{J} \approx 98.1\;\text{kJ}\)."),
 ],
  r"An welcher Stelle der Achterbahn ist die Geschwindigkeit am grössten — und warum?",
  r"Am tiefsten Punkt: dort ist die Lageenergie minimal und nach der Energieerhaltung die Bewegungsenergie maximal.")),
 ('arbeit', block([
   mc(r"Die Einheit von Arbeit und Energie ist …",
      [("A", r"Newton"), ("B", r"Joule"), ("C", r"Watt")],
      r"<strong>B.</strong> Arbeit und Energie misst man in Joule: \(1\;\text{J} = 1\;\text{N}\cdot\text{m}\)."),
   lueck(r"Arbeit wird verrichtet, wenn eine Kraft längs eines " + L + r" wirkt.",
      r"Weges — \(W = F\cdot s\)."),
   rech(r"Wie viele Joule sind \(1\;\text{kWh}\)?",
      r"\(1\;\text{kWh} = 1000\;\text{W} \cdot 3600\;\text{s} = 3.6\cdot 10^{6}\;\text{J} = 3.6\;\text{MJ}\)."),
 ],
  r"Du trägst eine schwere Kiste waagrecht mit konstanter Geschwindigkeit durch einen Raum. Verrichtest du physikalisch Hubarbeit?",
  r"Nein. Hubkraft (senkrecht) und Weg (waagrecht) stehen senkrecht zueinander: \(W = F s \cos 90° = 0\). (Die Muskeln ermüden trotzdem — das ist etwas anderes.)")),
 ('kinetisch', block([
   mc(r"Bei welchem Winkel zwischen Kraft und Weg wird die meiste Arbeit verrichtet?",
      [("A", r"\(0°\)"), ("B", r"\(45°\)"), ("C", r"\(90°\)")],
      r"<strong>A.</strong> Bei \(0°\) ist \(\cos\alpha = 1\) maximal; bei \(90°\) wird keine Arbeit verrichtet."),
   lueck(r"Nur die Kraftkomponente " + L + r" zum Weg verrichtet Arbeit.",
      r"parallel (längs) — \(W = F s \cos\alpha\)."),
   rech(r"Kraft \(F = 40\;\text{N}\) zieht eine Kiste \(s = 5\;\text{m}\) waagrecht (\(\alpha = 0\)). Arbeit?",
      r"\(W = F\cdot s = 40 \cdot 5 = 200\;\text{J}\)."),
 ],
  r"Eine Zugkraft von \(50\;\text{N}\) wirkt unter \(60°\) zum Weg über \(10\;\text{m}\). Welche Arbeit? (\(\cos 60° = 0.5\))",
  r"\(W = F s \cos\alpha = 50 \cdot 10 \cdot 0.5 = 250\;\text{J}\).")),
 ('erhaltung', block([
   mc(r"Verdoppelt man die Geschwindigkeit, so wird die kinetische Energie …",
      [("A", r"doppelt so gross"), ("B", r"viermal so gross"), ("C", r"gleich gross")],
      r"<strong>B.</strong> \(E_{\text{kin}} = \tfrac12 m v^2 \sim v^2\) — doppeltes \(v\), vierfache Energie."),
   lueck(r"Die kinetische Energie wächst " + L + r" mit der Geschwindigkeit.",
      r"quadratisch — \(E_{\text{kin}} = \tfrac12 m v^2\)."),
   rech(r"Kinetische Energie eines Autos (\(m = 1000\;\text{kg}\), \(v = 20\;\text{m/s}\))?",
      r"\(E_{\text{kin}} = \tfrac12 m v^2 = \tfrac12 \cdot 1000 \cdot 20^2 = 200\,000\;\text{J} = 200\;\text{kJ}\)."),
 ],
  r"Warum ist der Bremsweg bei doppeltem Tempo viermal so lang (bei gleicher Bremskraft)?",
  r"Die Bremsarbeit zehrt die kinetische Energie auf: \(F\cdot s = \tfrac12 m v^2\). Da \(E_{\text{kin}} \sim v^2\), gilt bei festem \(F\) auch \(s \sim v^2\).")),
 ('elastisch', block([
   mc(r"Ein reibungsfreies Pendel schwingt. Wo ist die kinetische Energie am grössten?",
      [("A", r"in den Umkehrpunkten"), ("B", r"im tiefsten Punkt"), ("C", r"überall gleich")],
      r"<strong>B.</strong> Im tiefsten Punkt ist die Lageenergie minimal, die kinetische Energie also maximal."),
   lueck(r"Bei der Energieerhaltung bleibt die " + L + r" aller Energieformen konstant.",
      r"Summe."),
   rech(r"Aus welcher Höhe fällt ein Körper, um \(v = 10\;\text{m/s}\) zu erreichen? (\(m g h = \tfrac12 m v^2\), \(g = 9.81\))",
      r"\(h = \dfrac{v^2}{2g} = \dfrac{10^2}{2 \cdot 9.81} \approx 5.1\;\text{m}\)."),
 ],
  r"Ein Skifahrer startet reibungsfrei aus der Ruhe auf \(h = 45\;\text{m}\). Geschwindigkeit am Hangfuss?",
  r"\(\tfrac12 m v^2 = m g h \Rightarrow v = \sqrt{2 g h} = \sqrt{2 \cdot 9.81 \cdot 45} \approx 29.7\;\text{m/s}\).")),
 ('leistung', block([
   mc(r"Verdoppelt man die Dehnung einer Feder, so wird die gespeicherte Energie …",
      [("A", r"doppelt so gross"), ("B", r"viermal so gross"), ("C", r"gleich gross")],
      r"<strong>B.</strong> \(E = \tfrac12 D s^2 \sim s^2\) — doppelte Dehnung, vierfache Energie."),
   lueck(r"Die Spannenergie einer Feder ist \(E = \tfrac12 D \cdot\) " + L + r".",
      r"\(s^2\)."),
   rech(r"Spannenergie einer Feder (\(D = 300\;\text{N/m}\), \(s = 0.2\;\text{m}\))?",
      r"\(E = \tfrac12 D s^2 = \tfrac12 \cdot 300 \cdot 0.2^2 = 6\;\text{J}\)."),
 ],
  r"Ein gespanntes Gummiband schleudert einen Ball weg. Wie hängen Spannenergie und Abschussgeschwindigkeit zusammen?",
  r"Spannenergie wird zu kinetischer Energie: \(\tfrac12 D s^2 = \tfrac12 m v^2 \Rightarrow v = s\sqrt{D/m}\). Doppelte Dehnung → doppelte Geschwindigkeit.")),
 ('wirkungsgrad', block([
   mc(r"Zwei Kräne heben dieselbe Last gleich hoch, Kran A schneller. Welcher hat die grössere Leistung?",
      [("A", r"Kran A"), ("B", r"Kran B"), ("C", r"beide gleich")],
      r"<strong>A.</strong> Gleiche Arbeit in kürzerer Zeit bedeutet grössere Leistung (\(P = W/t\))."),
   lueck(r"Leistung ist Arbeit pro " + L + r".",
      r"Zeit — \(P = W/t\)."),
   rech(r"Ein Motor verrichtet \(W = 6000\;\text{J}\) in \(t = 4\;\text{s}\). Leistung?",
      r"\(P = \dfrac{W}{t} = \dfrac{6000}{4} = 1500\;\text{W}\)."),
 ],
  r"Ein Lift hebt \(800\;\text{kg}\) in \(5\;\text{s}\) um \(15\;\text{m}\). Welche Leistung (ohne Verluste, \(g = 9.81\))?",
  r"\(W = m g h = 800 \cdot 9.81 \cdot 15 = 117\,720\;\text{J}\); \(\;\; P = \dfrac{W}{t} \approx 23\,544\;\text{W} \approx 23.5\;\text{kW}\).")),
 ('theorie', block([
   mc(r"Der Wirkungsgrad eines realen Geräts ist …",
      [("A", r"immer genau \(1\)"), ("B", r"immer kleiner als \(1\)"), ("C", r"manchmal grösser als \(1\)")],
      r"<strong>B.</strong> Ein Teil der Energie geht stets als Verlust (meist Wärme) verloren — \(\eta < 1\)."),
   lueck(r"Der Wirkungsgrad ist Nutzenergie geteilt durch " + L + r" Energie.",
      r"zugeführte — \(\eta = E_{\text{nutz}}/E_{\text{zu}}\)."),
   rech(r"Maschine erhält \(E_{\text{zu}} = 2000\;\text{J}\), liefert \(E_{\text{nutz}} = 1500\;\text{J}\). Wirkungsgrad?",
      r"\(\eta = \dfrac{1500}{2000} = 0.75 = 75\,\%\)."),
 ],
  r"Zwei Stufen mit \(\eta_1 = 0.8\) und \(\eta_2 = 0.5\) sind hintereinander. Gesamtwirkungsgrad?",
  r"Die Wirkungsgrade multiplizieren sich: \(\eta = 0.8 \cdot 0.5 = 0.4 = 40\,\%\).")),
 ('aufgaben', block([
   mc(r"Die Arbeit der resultierenden Kraft an einem Körper ist gleich der Änderung seiner …",
      [("A", r"Lageenergie"), ("B", r"kinetischen Energie"), ("C", r"Spannenergie")],
      r"<strong>B.</strong> Das ist der Arbeits-Energie-Satz: \(W = \Delta E_{\text{kin}}\)."),
   lueck(r"Der Arbeits-Energie-Satz lautet \(W = \Delta E_{\text{" + L + r"}}\) (Index).",
      r"kin — \(W = \Delta E_{\text{kin}}\)."),
   rech(r"Welche Arbeit beschleunigt \(m = 2\;\text{kg}\) von \(0\) auf \(v = 6\;\text{m/s}\)?",
      r"\(W = \tfrac12 m v^2 = \tfrac12 \cdot 2 \cdot 6^2 = 36\;\text{J}\)."),
 ],
  r"Leite aus \(W = F\cdot s\), \(F = m a\) und \(v^2 = 2 a s\) die kinetische Energie her.",
  r"\(W = F s = m a s\); mit \(a s = \tfrac12 v^2\) folgt \(W = \tfrac12 m v^2 = E_{\text{kin}}\).")),
]

# Zahlenprüfung
assert 2*3 == 6 and round(5*9.81,2) == 49.05 and 200*0.15 == 30 and 12/4 == 3 and 20/5 == 4 and 4*3 == 12
assert 0.3*50 == 15 and round(2*9.81*0.5,2) == 9.81 and round(math.degrees(math.atan(0.5)),1) == 26.6 and 60*2/40 == 3
assert 500*9.81*20 == 98100 and 1000*3600 == 3.6e6 and 40*5 == 200 and 50*10*0.5 == 250 and 0.5*1000*400 == 200000
assert round(100/(2*9.81),1) == 5.1 and round((2*9.81*45)**0.5,1) == 29.7 and 0.5*300*0.04 == 6 and 6000/4 == 1500
assert 800*9.81*15 == 117720 and round(117720/5,0) == 23544 and 1500/2000 == 0.75 and 0.8*0.5 == 0.4 and 0.5*2*36 == 36
print("Zahlen p4-2 & p4-3: OK")

for fn, pairs in [("themen/p4-2-dynamik.html", p42), ("themen/p4-3-energie.html", p43)]:
    n, do_, dc, oo, oc = apply_page(fn, pairs)
    print(f"{fn}: {n} Mini-Checks | div {do_}/{dc} {'OK' if do_==dc else 'DIFF'} | open( {oo}/{oc} {'OK' if oo==oc else 'DIFF'}")
