import sys
sys.path.insert(0, 'scripts')
from minicheck_lib import mc, lueck, rech, block, L, apply_page

p51 = [
 ('definition', block([
   mc(r"Das Zittern kleiner Teilchen im Wasser (Brown'sche Bewegung) zeigt:",
      [("A", r"das Wasser ist verschmutzt"), ("B", r"die Wassermoleküle sind in ständiger Bewegung"), ("C", r"das Licht schiebt die Teilchen")],
      r"<strong>B.</strong> Die unsichtbaren Wassermoleküle stossen die Teilchen unregelmässig an — sichtbarer Beleg für die ständige Teilchenbewegung."),
   lueck(r"Je höher die Temperatur, desto " + L + r" bewegen sich die Teilchen.",
      r"schneller (heftiger)."),
   rech(r"Welche Temperatur hat schmelzendes Eis (\(0°C\)) in Kelvin?",
      r"\(T = 0 + 273.15 = 273.15\;\text{K} \approx 273\;\text{K}\)."),
 ],
  r"Warum verteilt sich ein Tropfen Tinte in warmem Wasser schneller als in kaltem?",
  r"In warmem Wasser bewegen sich die Moleküle schneller; sie durchmischen die Tinte rascher (stärkere Diffusion).")),
 ('teilchen', block([
   mc(r"Temperatur ist ein Mass für …",
      [("A", r"die Wärmemenge"), ("B", r"die mittlere Bewegungsenergie der Teilchen"), ("C", r"die Masse")],
      r"<strong>B.</strong> Die Temperatur misst die mittlere kinetische Energie der Teilchen."),
   lueck(r"Die SI-Einheit der Temperatur ist das " + L + r".",
      r"Kelvin (K)."),
   rech(r"Körpertemperatur \(37°C\) in Kelvin?",
      r"\(T = 37 + 273.15 = 310.15\;\text{K} \approx 310\;\text{K}\)."),
 ],
  r"Zwei Körper unterschiedlicher Temperatur berühren sich. In welche Richtung fliesst die Wärme, und wann hört der Fluss auf?",
  r"Von warm nach kalt — so lange, bis beide dieselbe Temperatur haben (thermisches Gleichgewicht).")),
 ('aggregat', block([
   mc(r"Verdoppelt sich die absolute Temperatur (in K), so …",
      [("A", r"verdoppelt sich die mittlere kinetische Energie der Teilchen"), ("B", r"halbiert sie sich"), ("C", r"bleibt sie gleich")],
      r"<strong>A.</strong> Die mittlere Bewegungsenergie ist proportional zur absoluten Temperatur."),
   lueck(r"Die mittlere kinetische Energie der Teilchen ist proportional zur " + L + r" Temperatur.",
      r"absoluten (Kelvin-)."),
   rech(r"Ein Gas wird von \(300\;\text{K}\) auf \(600\;\text{K}\) erwärmt. Um welchen Faktor steigt die mittlere Bewegungsenergie?",
      r"Faktor \(\dfrac{600}{300} = 2\) — sie verdoppelt sich."),
 ],
  r"Warum lässt sich die Temperatur nicht beliebig weit absenken?",
  r"Bei \(0\;\text{K}\) ist die Teilchenbewegung minimal; eine noch geringere Bewegung gibt es nicht. Dieser absolute Nullpunkt ist die untere Grenze.")),
 ('skalen', block([
   mc(r"Beim Schmelzen von Eis bei \(0°C\) …",
      [("A", r"steigt die Temperatur"), ("B", r"bleibt die Temperatur konstant"), ("C", r"sinkt die Temperatur")],
      r"<strong>B.</strong> Während des Schmelzens bleibt die Temperatur bei \(0°C\) — die Energie bricht Bindungen auf."),
   lueck(r"Der Übergang fest → flüssig heisst " + L + r".",
      r"Schmelzen."),
   rech(r"Bei welcher Temperatur (in °C) siedet Wasser auf Meereshöhe?",
      r"Bei \(100°C\) (Normaldruck)."),
 ],
  r"Warum bleibt ein Eiswasser-Gemisch bei \(0°C\), obwohl man Wärme zuführt?",
  r"Die zugeführte Energie schmilzt zunächst das Eis (Schmelzwärme), statt die Temperatur zu erhöhen. Erst wenn alles Eis geschmolzen ist, steigt die Temperatur.")),
 ('umrechnen', block([
   mc(r"Ein Temperaturunterschied von \(1°C\) entspricht …",
      [("A", r"\(1\;\text{K}\)"), ("B", r"\(274\;\text{K}\)"), ("C", r"\(273\;\text{K}\)")],
      r"<strong>A.</strong> Die Skalenschritte sind gleich gross: eine Differenz von \(1°C\) ist \(1\;\text{K}\)."),
   lueck(r"Die Kelvin-Skala beginnt beim " + L + r" Nullpunkt.",
      r"absoluten."),
   rech(r"Wie viele Kelvin sind \(100°C\)?",
      r"\(T = 100 + 273.15 = 373.15\;\text{K} \approx 373\;\text{K}\)."),
 ],
  r"Warum gibt man Temperaturdifferenzen in Kelvin an, auch wenn man in °C gemessen hat?",
  r"Die Schrittweiten sind identisch (\(1°C = 1\;\text{K}\)), eine Differenz ist also zahlengleich. Kelvin ist aber die SI-Einheit und vermeidet das negative Vorzeichen.")),
 ('nullpunkt', block([
   mc(r"\(0\;\text{K}\) entsprechen …",
      [("A", r"\(0°C\)"), ("B", r"\(-273.15°C\)"), ("C", r"\(273.15°C\)")],
      r"<strong>B.</strong> Der absolute Nullpunkt liegt bei \(-273.15°C\)."),
   lueck(r"Umrechnung: \(T/\text{K} = \vartheta/°C + \) " + L + r".",
      r"\(273.15\)."),
   rech(r"\(-40°C\) in Kelvin?",
      r"\(T = -40 + 273.15 = 233.15\;\text{K} \approx 233\;\text{K}\)."),
 ],
  r"Bei welcher Temperatur zeigen Celsius- und Fahrenheit-Skala denselben Zahlenwert? (\(\vartheta_F = 1.8\,\vartheta_C + 32\))",
  r"Gleichsetzen: \(\vartheta = 1.8\,\vartheta + 32 \Rightarrow -0.8\,\vartheta = 32 \Rightarrow \vartheta = -40\). Also \(-40°C = -40°F\).")),
 ('aufgaben', block([
   mc(r"Den absoluten Nullpunkt findet man, indem man …",
      [("A", r"Druck (oder Volumen) eines Gases gegen die Temperatur aufträgt und die Gerade bis null verlängert"), ("B", r"das kälteste Eis misst"), ("C", r"den Mittelwert vieler Messungen nimmt")],
      r"<strong>A.</strong> Die \(p\)-\(T\)-Gerade eines Gases extrapoliert man bis \(p = 0\) — das ergibt \(-273.15°C\)."),
   lueck(r"Der absolute Nullpunkt liegt bei \(-273.15°C\), also bei \(0\) " + L + r".",
      r"Kelvin (K)."),
   rech(r"Bei \(0°C\) hat ein Gas den Druck \(p_0\). Bei welcher Temperatur (°C) wäre der Druck extrapoliert null?",
      r"Bei \(-273.15°C\) — dem absoluten Nullpunkt."),
 ],
  r"Zwei Gase mit verschiedenem Anfangsdruck ergeben im \(p\)-\(T\)-Diagramm zwei Geraden. Warum schneiden beide die Temperaturachse im selben Punkt?",
  r"Beide extrapolieren auf \(p = 0\) beim absoluten Nullpunkt (\(-273.15°C\)). Dieser ist eine universelle Konstante — unabhängig von Gas und Anfangsdruck.")),
]

p52 = [
 ('definition', block([
   mc(r"Warum wird der Metalllöffel in der heissen Suppe heiss?",
      [("A", r"durch Strahlung"), ("B", r"durch Wärmeleitung"), ("C", r"durch Verdunstung")],
      r"<strong>B.</strong> Im Metall wird die Wärme von Teilchen zu Teilchen weitergegeben — Wärmeleitung."),
   lueck(r"Wärme fliesst von selbst stets von " + L + r" nach kalt.",
      r"warm (heiss)."),
   rech(r"Wie viel Wärme braucht es, um \(1\;\text{kg}\) Wasser um \(1\;\text{K}\) zu erwärmen? (\(c = 4180\;\text{J/(kg·K)}\))",
      r"\(Q = c\,m\,\Delta T = 4180 \cdot 1 \cdot 1 = 4180\;\text{J}\)."),
 ],
  r"Warum fühlt sich ein Metallgeländer kälter an als ein Holzgeländer gleicher Temperatur?",
  r"Metall leitet die Wärme viel besser und führt sie schneller von der Hand weg. Die Temperatur ist gleich — nur das Wärmegefühl unterscheidet sich.")),
 ('waermemenge', block([
   mc(r"Wärme ist …",
      [("A", r"eine im Körper gespeicherte Grösse"), ("B", r"übertragene Energie (eine Prozessgrösse)"), ("C", r"dasselbe wie Temperatur")],
      r"<strong>B.</strong> Wärme ist die zwischen Körpern übertragene Energie; gespeichert wird die innere Energie."),
   lueck(r"Wärme wird in der Einheit " + L + r" gemessen.",
      r"Joule (J)."),
   rech(r"Welche Wärme nimmt \(2\;\text{kg}\) Wasser bei \(\Delta T = 5\;\text{K}\) auf? (\(c = 4180\))",
      r"\(Q = c\,m\,\Delta T = 4180 \cdot 2 \cdot 5 = 41\,800\;\text{J} = 41.8\;\text{kJ}\)."),
 ],
  r"Warum sagt man, ein Körper „enthält“ keine Wärme, wohl aber innere Energie?",
  r"Wärme bezeichnet die übertragene Energie (Prozessgrösse) zwischen Körpern. Gespeichert ist die innere Energie. „Wärme im Körper“ ist daher physikalisch ungenau.")),
 ('mischung', block([
   mc(r"Bei gleicher Wärmezufuhr erwärmt sich am stärksten der Stoff mit …",
      [("A", r"grosser spezifischer Wärmekapazität"), ("B", r"kleiner spezifischer Wärmekapazität"), ("C", r"grosser Masse")],
      r"<strong>B.</strong> Aus \(\Delta T = Q/(c\,m)\): kleines \(c\) → grosse Temperaturänderung."),
   lueck(r"Die zugeführte Wärme ist \(Q = c \cdot m \cdot\) " + L + r".",
      r"\(\Delta T\)."),
   rech(r"Wärme, um \(0.5\;\text{kg}\) Wasser von \(20°C\) auf \(80°C\) zu erwärmen? (\(c = 4180\))",
      r"\(Q = c\,m\,\Delta T = 4180 \cdot 0.5 \cdot 60 = 125\,400\;\text{J} \approx 125.4\;\text{kJ}\)."),
 ],
  r"Wasser (\(c = 4180\)) und Sand (\(c \approx 800\)) bekommen gleich viel Sonne. Was wird schneller heiss — und warum kühlt das Meer langsamer ab als der Strand?",
  r"Sand erwärmt sich schneller (kleineres \(c\)). Wasser speichert pro Grad viel mehr Energie, deshalb erwärmt und kühlt es sich träger.")),
 ('heizkurve', block([
   mc(r"Mischt man gleiche Massen heisses und kaltes Wasser, liegt die Mischtemperatur …",
      [("A", r"näher beim heissen"), ("B", r"genau in der Mitte"), ("C", r"näher beim kalten")],
      r"<strong>B.</strong> Bei gleichen Massen und gleichem \(c\) liegt die Mischtemperatur genau dazwischen."),
   lueck(r"Beim Mischen gibt der wärmere Körper genau so viel Wärme ab, wie der kältere " + L + r".",
      r"aufnimmt."),
   rech(r"\(1\;\text{kg}\) Wasser bei \(80°C\) + \(1\;\text{kg}\) Wasser bei \(20°C\). Mischtemperatur?",
      r"\(T = \dfrac{80 + 20}{2} = 50°C\)."),
 ],
  r"\(2\;\text{kg}\) Wasser bei \(20°C\) werden mit \(1\;\text{kg}\) Wasser bei \(80°C\) gemischt (gleiches \(c\)). Mischtemperatur?",
  r"Gewichtetes Mittel: \(T = \dfrac{2 \cdot 20 + 1 \cdot 80}{3} = \dfrac{120}{3} = 40°C\).")),
 ('transport', block([
   mc(r"Während Wasser bei \(100°C\) siedet, …",
      [("A", r"steigt die Temperatur weiter"), ("B", r"bleibt die Temperatur konstant"), ("C", r"sinkt sie")],
      r"<strong>B.</strong> Die Verdampfungswärme wird zum Phasenwechsel verbraucht — die Temperatur bleibt konstant."),
   lueck(r"Die Wärme für einen Phasenwechsel ist \(Q = m \cdot\) " + L + r".",
      r"\(L\) (spezifische Umwandlungswärme)."),
   rech(r"Wärme, um \(0.2\;\text{kg}\) Eis bei \(0°C\) zu schmelzen? (\(L_S = 334\;\text{kJ/kg}\))",
      r"\(Q = m\,L_S = 0.2 \cdot 334 = 66.8\;\text{kJ}\)."),
 ],
  r"Warum kühlt Schwitzen den Körper, obwohl der Schweiss zunächst körperwarm ist?",
  r"Das Verdunsten entzieht Verdampfungswärme (\(Q = m\,L_V\)). Diese Energie kommt aus der Haut, die dadurch abkühlt.")),
 ('wirkungsgrad', block([
   mc(r"Wie gelangt die Sonnenwärme durch das Vakuum des Weltraums zur Erde?",
      [("A", r"durch Wärmeleitung"), ("B", r"durch Konvektion"), ("C", r"durch Strahlung")],
      r"<strong>C.</strong> Strahlung braucht kein Medium und überquert das Vakuum."),
   lueck(r"Die drei Arten des Wärmetransports sind Leitung, " + L + r" und Strahlung.",
      r"Konvektion (Strömung)."),
   rech(r"Welche der drei Transportarten funktioniert ohne Materie?",
      r"Die Wärmestrahlung — sie benötigt kein Medium."),
 ],
  r"Warum sind gute Thermoskannen doppelwandig mit Vakuum dazwischen und innen verspiegelt?",
  r"Das Vakuum unterbindet Leitung und Konvektion, die Verspiegelung reflektiert die Wärmestrahlung — alle drei Transportwege werden gebremst.")),
 ('treibhaus', block([
   mc(r"Der Wirkungsgrad einer Wärmekraftmaschine ist …",
      [("A", r"immer \(100\,\%\)"), ("B", r"stets kleiner als \(100\,\%\)"), ("C", r"beliebig grösser als \(100\,\%\)")],
      r"<strong>B.</strong> Ein Teil der Wärme geht stets als Abwärme verloren — \(\eta < 1\)."),
   lueck(r"Ein Teil der zugeführten Wärme geht stets als " + L + r" verloren.",
      r"Abwärme."),
   rech(r"Eine Maschine nimmt \(1000\;\text{J}\) Wärme auf und leistet \(300\;\text{J}\) Arbeit. Wirkungsgrad?",
      r"\(\eta = \dfrac{300}{1000} = 0.3 = 30\,\%\)."),
 ],
  r"Eine Wärmepumpe liefert mehr Heizwärme, als sie elektrische Energie verbraucht. Widerspricht das dem Energieerhaltungssatz?",
  r"Nein. Sie verschiebt zusätzlich Wärme aus der Umgebung ins Haus. Geliefert wird Strom plus Umgebungswärme — es wird keine Energie erzeugt, nur transportiert.")),
 ('aufgaben', block([
   mc(r"Der natürliche Treibhauseffekt bewirkt, dass die Erde …",
      [("A", r"kälter ist als ohne Atmosphäre"), ("B", r"wärmer ist als ohne Atmosphäre"), ("C", r"gleich warm ist")],
      r"<strong>B.</strong> Ohne Treibhausgase wäre die Erdoberfläche im Mittel deutlich kälter."),
   lueck(r"Treibhausgase lassen Sonnenlicht durch, halten aber die " + L + r" Strahlung der Erde zurück.",
      r"infrarote (Wärme-)."),
   rech(r"In welchem Wellenlängenbereich strahlt die warme Erdoberfläche hauptsächlich ab?",
      r"Im Infrarot (langwellig) — anders als die kurzwellige Sonneneinstrahlung."),
 ],
  r"Warum wird es in einem geschlossenen Auto in der Sonne so heiss?",
  r"Das Glas lässt sichtbares Licht herein; die aufgeheizten Innenflächen strahlen Infrarot ab, das das Glas kaum durchlässt. Die Wärme staut sich — analog zum Treibhauseffekt.")),
]

assert round(0+273.15,2) == 273.15 and round(37+273.15,2) == 310.15 and 600/300 == 2 and round(100+273.15,2) == 373.15 and round(-40+273.15,2) == 233.15
assert 32/0.8 == 40
assert 4180*1*1 == 4180 and 4180*2*5 == 41800 and 4180*0.5*60 == 125400 and (80+20)/2 == 50 and (2*20+80)/3 == 40
assert round(0.2*334,1) == 66.8 and 300/1000 == 0.3
print("Zahlen p5-1 & p5-2: OK")

for fn, pairs in [("themen/p5-1-temperatur.html", p51), ("themen/p5-2-waerme.html", p52)]:
    n, do_, dc, oo, oc = apply_page(fn, pairs)
    print(f"{fn}: {n} Mini-Checks | div {do_}/{dc} {'OK' if do_==dc else 'DIFF'} | open( {oo}/{oc} {'OK' if oo==oc else 'DIFF'}")
