import sys, math
sys.path.insert(0, 'scripts')
from minicheck_lib import mc, lueck, rech, block, L, apply_page

p44 = [
 ('definition', block([
   mc(r"Damit eine Wippe im Gleichgewicht ist, muss gelten:",
      [("A", r"beide Massen sind gleich"), ("B", r"beide Produkte aus Kraft und Hebelarm sind gleich"), ("C", r"beide Abstände sind gleich")],
      r"<strong>B.</strong> Gleichgewicht heisst gleiche Drehmomente: \(F_1 r_1 = F_2 r_2\)."),
   lueck(r"Im Gleichgewicht ist die Summe der " + L + r" null.",
      r"Drehmomente."),
   rech(r"Ein Kind drückt links mit \(F_1 = 300\;\text{N}\) im Abstand \(r_1 = 1.5\;\text{m}\). Welches Drehmoment?",
      r"\(M = F_1 \cdot r_1 = 300 \cdot 1.5 = 450\;\text{N}\,\text{m}\)."),
 ],
  r"Ein Kind (\(25\;\text{kg}\)) sitzt \(1.5\;\text{m}\) von der Achse. Wo muss ein \(30\;\text{kg}\)-Kind sitzen, damit Gleichgewicht herrscht?",
  r"\(m_1 r_1 = m_2 r_2 \Rightarrow r_2 = \dfrac{25 \cdot 1.5}{30} = 1.25\;\text{m}\) — das schwerere Kind sitzt näher an der Achse.")),
 ('komponenten', block([
   mc(r"Ein starrer Körper ist im Gleichgewicht, wenn …",
      [("A", r"nur die Summe der Kräfte null ist"), ("B", r"Summe der Kräfte und Summe der Momente null sind"), ("C", r"er sich gleichförmig dreht")],
      r"<strong>B.</strong> Beim starren Körper müssen \(\sum \vec F = 0\) und \(\sum M = 0\) gelten."),
   lueck(r"Das Drehmoment ist das Produkt aus Kraft und " + L + r".",
      r"Hebelarm — \(M = F \cdot r\)."),
   rech(r"Kraft \(20\;\text{N}\), Hebelarm \(0.4\;\text{m}\). Welches Drehmoment?",
      r"\(M = F \cdot r = 20 \cdot 0.4 = 8\;\text{N}\,\text{m}\)."),
 ],
  r"Warum lässt sich eine Tür am Griff (weit von den Angeln) leichter öffnen als nahe den Angeln?",
  r"Am Griff ist der Hebelarm \(r\) gross; bei gleicher Kraft ist das Moment \(M = F\,r\) grösser. Nahe den Angeln bräuchte man für dasselbe Moment viel mehr Kraft.")),
 ('resultierende', block([
   mc(r"Eine Kraft wirkt waagrecht (\(0°\) zur Horizontalen). Ihre senkrechte Komponente ist …",
      [("A", r"maximal"), ("B", r"null"), ("C", r"gleich \(F\)")],
      r"<strong>B.</strong> \(F_y = F \sin 0° = 0\) — eine waagrechte Kraft hat keine senkrechte Komponente."),
   lueck(r"Die waagrechte Komponente ist \(F_x = F \cdot\) " + L + r" des Winkels.",
      r"dem Kosinus — \(F_x = F\cos\varphi\)."),
   rech(r"\(F = 100\;\text{N}\) unter \(\varphi = 30°\). Komponenten? (\(\cos 30° \approx 0.87\), \(\sin 30° = 0.5\))",
      r"\(F_x = F\cos\varphi \approx 87\;\text{N}\), \(\;\; F_y = F\sin\varphi = 50\;\text{N}\)."),
 ],
  r"Eine Kraft hat die Komponenten \(F_x = 3\;\text{N}\) und \(F_y = 4\;\text{N}\). Wie gross ist ihr Betrag?",
  r"\(F = \sqrt{F_x^2 + F_y^2} = \sqrt{9 + 16} = 5\;\text{N}\).")),
 ('punkt', block([
   mc(r"Zwei gleich grosse Kräfte wirken in genau entgegengesetzte Richtung. Die Resultierende ist …",
      [("A", r"doppelt so gross"), ("B", r"null"), ("C", r"gleich gross wie eine Kraft")],
      r"<strong>B.</strong> Entgegengesetzt gleich grosse Kräfte heben sich auf: \(\vec F_R = 0\)."),
   lueck(r"Kräfte werden " + L + r" addiert (Parallelogramm).",
      r"vektoriell."),
   rech(r"Zwei Kräfte \(6\;\text{N}\) und \(8\;\text{N}\) wirken senkrecht zueinander. Resultierende?",
      r"\(F_R = \sqrt{6^2 + 8^2} = \sqrt{36 + 64} = 10\;\text{N}\)."),
 ],
  r"Zwei Kräfte (je \(5\;\text{N}\)) schliessen einen Winkel von \(60°\) ein. Wie gross ist die Resultierende? (\(\cos 60° = 0.5\))",
  r"\(F_R = \sqrt{F_1^2 + F_2^2 + 2 F_1 F_2 \cos 60°} = \sqrt{25 + 25 + 25} = \sqrt{75} \approx 8.7\;\text{N}\).")),
 ('drehmoment', block([
   mc(r"An einem Knoten herrscht Kräftegleichgewicht, wenn …",
      [("A", r"die grösste Kraft wegfällt"), ("B", r"die Summe aller Kräfte null ist"), ("C", r"alle Kräfte gleich gross sind")],
      r"<strong>B.</strong> Gleichgewicht am Punkt bedeutet \(\sum \vec F = 0\)."),
   lueck(r"Die drei Kräfte am Knoten bilden ein geschlossenes " + L + r".",
      r"Kräftedreieck."),
   rech(r"Eine Last \(100\;\text{N}\) hängt symmetrisch an zwei Seilen, jedes unter \(60°\) zur Waagrechten. Welche vertikale Komponente trägt jedes Seil?",
      r"Je \(50\;\text{N}\) vertikal (zusammen \(100\;\text{N}\)). Die Seilkraft selbst ist \(\dfrac{50}{\sin 60°} \approx 57.7\;\text{N}\)."),
 ],
  r"Was passiert mit den Seilkräften, wenn man die beiden Seile fast waagrecht spannt?",
  r"Sie werden sehr gross. Die vertikale Komponente \(F\sin\alpha\) muss die Last tragen; bei kleinem \(\alpha\) braucht es dafür eine sehr grosse Seilkraft \(F\).")),
 ('hebel', block([
   mc(r"Das Drehmoment ist maximal, wenn die Kraft zum Hebel im Winkel … steht.",
      [("A", r"\(0°\)"), ("B", r"\(45°\)"), ("C", r"\(90°\)")],
      r"<strong>C.</strong> Bei \(90°\) ist \(\sin\alpha = 1\) — die Kraft steht senkrecht zum Hebel, das Moment ist maximal."),
   lueck(r"Das Drehmoment ist \(M = F \cdot l \cdot\) " + L + r" des Angriffswinkels.",
      r"dem Sinus — \(M = F\,l \sin\alpha\)."),
   rech(r"\(F = 20\;\text{N}\), \(l = 0.5\;\text{m}\), \(\alpha = 90°\). Drehmoment?",
      r"\(M = F \cdot l = 20 \cdot 0.5 = 10\;\text{N}\,\text{m}\)."),
 ],
  r"Dieselbe Kraft greift am selben Hebel einmal unter \(90°\), einmal unter \(30°\) an. Wie verhalten sich die Momente? (\(\sin 30° = 0.5\))",
  r"Bei \(30°\) ist das Moment nur halb so gross: \(\dfrac{\sin 30°}{\sin 90°} = \dfrac{0.5}{1} = 0.5\).")),
 ('auflager', block([
   mc(r"Ein langer Kraftarm bedeutet …",
      [("A", r"man braucht mehr Kraft"), ("B", r"man braucht weniger Kraft"), ("C", r"keinen Unterschied")],
      r"<strong>B.</strong> Bei längerem Kraftarm genügt weniger Kraft für dasselbe Moment — das Prinzip jeder Hebelmaschine."),
   lueck(r"Das Hebelgesetz lautet \(F_1 r_1 = F_2 \cdot\) " + L + r".",
      r"\(r_2\)."),
   rech(r"\(F_1 = 40\;\text{N}\) bei \(r_1 = 0.30\;\text{m}\). Welche Kraft \(F_2\) hält bei \(r_2 = 0.60\;\text{m}\) das Gleichgewicht?",
      r"\(F_2 = \dfrac{F_1 r_1}{r_2} = \dfrac{40 \cdot 0.30}{0.60} = 20\;\text{N}\)."),
 ],
  r"Schubkarre: Last \(600\;\text{N}\) im Abstand \(0.4\;\text{m}\) vom Rad, die Griffe sind \(1.2\;\text{m}\) vom Rad entfernt. Welche Hubkraft an den Griffen?",
  r"\(F = \dfrac{600 \cdot 0.4}{1.2} = 200\;\text{N}\) — der lange Griff-Hebelarm spart Kraft.")),
 ('schiefe-ebene', block([
   mc(r"Eine Last sitzt näher bei Stütze A. Welche Stütze trägt mehr?",
      [("A", r"Stütze A"), ("B", r"Stütze B"), ("C", r"beide gleich")],
      r"<strong>A.</strong> Die nähere Stütze trägt den grösseren Anteil der Last."),
   lueck(r"Die Summe der beiden Auflagerkräfte ist gleich der " + L + r".",
      r"Gesamtlast — \(F_A + F_B = F\)."),
   rech(r"Balken \(4\;\text{m}\), Last \(200\;\text{N}\) genau in der Mitte. Auflagerkräfte?",
      r"Symmetrisch: \(F_A = F_B = 100\;\text{N}\)."),
 ],
  r"Eine Last \(300\;\text{N}\) sitzt \(1\;\text{m}\) von A entfernt auf einem \(4\;\text{m}\)-Balken. Wie gross sind die Auflagerkräfte?",
  r"Momente um A: \(F_B \cdot 4 = 300 \cdot 1 \Rightarrow F_B = 75\;\text{N}\); \(\;\; F_A = 300 - 75 = 225\;\text{N}\).")),
 ('aufgaben', block([
   mc(r"Ein Klotz auf der schiefen Ebene rutscht, sobald …",
      [("A", r"\(\tan\alpha > \mu_H\)"), ("B", r"\(\alpha > 90°\)"), ("C", r"die Masse gross genug ist")],
      r"<strong>A.</strong> Rutschbeginn bei \(\tan\alpha > \mu_H\) — unabhängig von der Masse."),
   lueck(r"Der Grenzwinkel hängt nur von der " + L + r" ab, nicht von der Masse.",
      r"Haftreibungszahl \(\mu_H\)."),
   rech(r"\(\mu_H = 0.6\). Ab welchem Neigungswinkel rutscht der Klotz?",
      r"\(\alpha = \arctan(\mu_H) = \arctan(0.6) \approx 31°\)."),
 ],
  r"Ein Klotz (\(m = 3\;\text{kg}\)) liegt auf einer Ebene mit \(\alpha = 20°\), \(\mu_H = 0.5\). Haftet oder rutscht er? (\(\tan 20° \approx 0.36\))",
  r"\(\tan 20° \approx 0.36 < 0.5 = \mu_H\) → der Klotz haftet (die Haftreibung reicht aus).")),
]

p45 = [
 ('definition', block([
   mc(r"Je tiefer man taucht, desto …",
      [("A", r"kleiner der Druck"), ("B", r"grösser der Druck"), ("C", r"bleibt der Druck gleich")],
      r"<strong>B.</strong> Der Schweredruck wächst linear mit der Tiefe: \(p = \rho g h\)."),
   lueck(r"Der Schweredruck nimmt mit der " + L + r" zu.",
      r"Tiefe."),
   rech(r"Druck in \(h = 10\;\text{m}\) Wassertiefe? (\(\rho = 1000\), \(g = 9.81\))",
      r"\(p = \rho g h = 1000 \cdot 9.81 \cdot 10 = 98\,100\;\text{Pa} \approx 0.98\;\text{bar}\)."),
 ],
  r"Warum schmerzen die Ohren beim Tauchen schon nach wenigen Metern?",
  r"Der Schweredruck steigt rasch (pro \(10\;\text{m}\) rund \(1\;\text{bar}\)). Der Druckunterschied zum luftgefüllten Mittelohr drückt aufs Trommelfell — daher der nötige Druckausgleich.")),
 ('schweredruck', block([
   mc(r"Die Einheit des Drucks ist …",
      [("A", r"Newton"), ("B", r"Pascal"), ("C", r"Joule")],
      r"<strong>B.</strong> Druck wird in Pascal gemessen: \(1\;\text{Pa} = 1\;\text{N/m}^2\)."),
   lueck(r"Druck ist Kraft pro " + L + r".",
      r"Fläche — \(p = F/A\)."),
   rech(r"Eine Kraft \(50\;\text{N}\) wirkt auf \(A = 0.01\;\text{m}^2\). Welcher Druck?",
      r"\(p = \dfrac{F}{A} = \dfrac{50}{0.01} = 5000\;\text{Pa}\)."),
 ],
  r"Warum sinkt man mit Schneeschuhen weniger in den Schnee ein als mit normalen Schuhen?",
  r"Die grössere Fläche verteilt dieselbe Gewichtskraft: \(p = F/A\) wird kleiner, der Schnee gibt weniger nach.")),
 ('paradoxon', block([
   mc(r"Wovon hängt der Schweredruck NICHT ab?",
      [("A", r"von der Tiefe"), ("B", r"von der Dichte der Flüssigkeit"), ("C", r"von der Gefässform")],
      r"<strong>C.</strong> \(p = \rho g h\) — die Form des Gefässes kommt nicht vor."),
   lueck(r"Der Schweredruck ist \(p = \rho \cdot g \cdot\) " + L + r".",
      r"\(h\) (Tiefe)."),
   rech(r"Druck am Boden eines \(2\;\text{m}\) tiefen Ölbeckens (\(\rho = 900\), \(g = 9.81\))?",
      r"\(p = \rho g h = 900 \cdot 9.81 \cdot 2 = 17\,658\;\text{Pa} \approx 17.7\;\text{kPa}\)."),
 ],
  r"In welcher Wassertiefe herrscht ein Schweredruck von \(2\;\text{bar}\) (\(= 2\cdot 10^5\;\text{Pa}\))? (\(\rho = 1000\), \(g = 9.81\))",
  r"\(h = \dfrac{p}{\rho g} = \dfrac{2\cdot 10^5}{1000 \cdot 9.81} \approx 20.4\;\text{m}\).")),
 ('pascal', block([
   mc(r"Drei verschieden geformte Gefässe haben gleiche Füllhöhe. Der Bodendruck ist …",
      [("A", r"im breitesten am grössten"), ("B", r"überall gleich"), ("C", r"im schmalsten am grössten")],
      r"<strong>B.</strong> Hydrostatisches Paradoxon: bei gleicher Höhe ist der Bodendruck gleich (\(p = \rho g h\))."),
   lueck(r"Der Bodendruck hängt nur von der " + L + r" ab, nicht von der Wassermenge.",
      r"Füllhöhe."),
   rech(r"Zwei Gefässe sind beide \(0.5\;\text{m}\) hoch gefüllt. Verhältnis der Bodendrücke?",
      r"\(1 : 1\) — gleiche Höhe, gleicher Druck, unabhängig von der Menge."),
 ],
  r"Ein dünnes hohes Rohr und ein breites Fass haben gleiche Wasserhöhe. Warum ist der Bodendruck gleich, obwohl im Fass viel mehr Wasser ist?",
  r"Der Druck hängt nur von der Höhe ab (\(p = \rho g h\)). Das zusätzliche Wasser im Fass ruht auf dessen breiterem Boden und erhöht den Druck pro Fläche nicht.")),
 ('auftrieb', block([
   mc(r"Bei der hydraulischen Presse gewinnt man Kraft auf Kosten von …",
      [("A", r"Druck"), ("B", r"Weg"), ("C", r"Energie")],
      r"<strong>B.</strong> Die Kraft wird verstärkt, der Weg am grossen Kolben wird entsprechend kleiner (Energieerhaltung)."),
   lueck(r"Nach dem Prinzip von Pascal ist der " + L + r" in der Flüssigkeit überall gleich.",
      r"Druck."),
   rech(r"\(F_1 = 100\;\text{N}\) auf \(A_1\); der grosse Kolben hat \(A_2 = 5\,A_1\). Ausgangskraft \(F_2\)?",
      r"\(F_2 = F_1 \cdot \dfrac{A_2}{A_1} = 100 \cdot 5 = 500\;\text{N}\)."),
 ],
  r"Der kleine Kolben wird um \(20\;\text{cm}\) gedrückt, \(A_2 = 5\,A_1\). Um wie viel hebt sich der grosse Kolben?",
  r"Gleiches Volumen: \(s_2 = s_1 \cdot \dfrac{A_1}{A_2} = \dfrac{20\;\text{cm}}{5} = 4\;\text{cm}\) — mehr Kraft, dafür weniger Weg.")),
 ('schwimmen', block([
   mc(r"Die Auftriebskraft entspricht …",
      [("A", r"dem Gewicht des Körpers"), ("B", r"dem Gewicht der verdrängten Flüssigkeit"), ("C", r"dem Volumen des Körpers")],
      r"<strong>B.</strong> Archimedisches Prinzip: \(F_A = \rho_{\text{Fl}}\,V_e\,g\) = Gewicht der verdrängten Flüssigkeit."),
   lueck(r"Die Auftriebskraft ist \(F_A = \rho_{\text{Fl}} \cdot V_e \cdot\) " + L + r".",
      r"\(g\)."),
   rech(r"Ein Körper verdrängt \(V = 2\;\text{L} = 0.002\;\text{m}^3\) Wasser. Auftriebskraft? (\(\rho = 1000\), \(g = 9.81\))",
      r"\(F_A = \rho V g = 1000 \cdot 0.002 \cdot 9.81 = 19.62\;\text{N}\)."),
 ],
  r"Ein \(10\;\text{kg}\)-Stein (\(V = 4\;\text{L}\)) liegt unter Wasser. Welche Kraft braucht man, um ihn zu halten? (\(g = 9.81\))",
  r"Gewicht \(98.1\;\text{N}\), Auftrieb \(1000 \cdot 0.004 \cdot 9.81 = 39.24\;\text{N}\). Haltekraft \(= 98.1 - 39.24 \approx 58.9\;\text{N}\).")),
 ('u-rohr', block([
   mc(r"Ein Körper schwimmt, wenn seine Dichte …",
      [("A", r"grösser als die der Flüssigkeit ist"), ("B", r"kleiner als die der Flüssigkeit ist"), ("C", r"egal ist")],
      r"<strong>B.</strong> Kleinere Dichte als die Flüssigkeit → der Körper schwimmt."),
   lueck(r"Ein Körper schwebt, wenn seine Dichte " + L + r" der Flüssigkeitsdichte ist.",
      r"gleich."),
   rech(r"Ein Eiswürfel (\(\rho = 917\;\text{kg/m}^3\)) schwimmt auf Wasser (\(1000\)). Welcher Volumenanteil taucht ein?",
      r"Anteil \(= \dfrac{\rho_K}{\rho_{\text{Fl}}} = \dfrac{917}{1000} = 0.917 = 91.7\,\%\)."),
 ],
  r"Warum schwimmt ein Schiff aus Stahl, obwohl Stahl viel dichter als Wasser ist?",
  r"Entscheidend ist die mittlere Dichte des Schiffs (Stahl plus eingeschlossene Luft). Diese ist kleiner als Wasser, daher verdrängt der Rumpf genug Wasser für ausreichend Auftrieb.")),
 ('aufgaben', block([
   mc(r"Im U-Rohr mit zwei Flüssigkeiten steht die leichtere Flüssigkeit …",
      [("A", r"tiefer"), ("B", r"höher"), ("C", r"gleich hoch")],
      r"<strong>B.</strong> Bei gleichem Bodendruck steht die leichtere (kleinere Dichte) Flüssigkeit höher."),
   lueck(r"Im Gleichgewicht sind die " + L + r" auf beiden Seiten gleich.",
      r"Schweredrücke — \(\rho_1 h_1 = \rho_2 h_2\)."),
   rech(r"Öl (\(\rho = 800\)) steht \(10\;\text{cm}\) hoch. Wie hoch steht Wasser (\(1000\)) auf der anderen Seite?",
      r"\(\rho_{\text{Öl}} h_{\text{Öl}} = \rho_W h_W \Rightarrow h_W = \dfrac{800 \cdot 10}{1000} = 8\;\text{cm}\)."),
 ],
  r"Im U-Rohr steht Öl \(12\;\text{cm}\) und Wasser \(9.6\;\text{cm}\) hoch. Wie gross ist die Öldichte? (Wasser \(1000\))",
  r"\(\rho_{\text{Öl}} = \rho_W \cdot \dfrac{h_W}{h_{\text{Öl}}} = 1000 \cdot \dfrac{9.6}{12} = 800\;\text{kg/m}^3\).")),
]

assert 300*1.5 == 450 and 25*1.5/30 == 1.25 and 20*0.4 == 8 and round(100*0.87) == 87 and 100*0.5 == 50
assert (9+16)**0.5 == 5 and (36+64)**0.5 == 10 and round(75**0.5,1) == 8.7 and round(50/math.sin(math.radians(60)),1) == 57.7
assert 20*0.5 == 10 and 40*0.30/0.60 == 20 and 600*0.4/1.2 == 200 and 300*1/4 == 75 and 300-75 == 225 and round(math.degrees(math.atan(0.6))) == 31
assert 1000*9.81*10 == 98100 and 50/0.01 == 5000 and 900*9.81*2 == 17658 and round(2e5/(1000*9.81),1) == 20.4
assert 100*5 == 500 and 20/5 == 4 and round(1000*0.002*9.81,2) == 19.62 and round(98.1-39.24,2) == 58.86 and 917/1000 == 0.917
assert 800*10/1000 == 8 and 1000*9.6/12 == 800
print("Zahlen p4-4 & p4-5: OK")

for fn, pairs in [("themen/p4-4-statik.html", p44), ("themen/p4-5-hydrostatik.html", p45)]:
    n, do_, dc, oo, oc = apply_page(fn, pairs)
    print(f"{fn}: {n} Mini-Checks | div {do_}/{dc} {'OK' if do_==dc else 'DIFF'} | open( {oo}/{oc} {'OK' if oo==oc else 'DIFF'}")
